/* eslint-disable @next/next/no-img-element */
'use client';
import { useEffect, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { Shield, Users, Ticket, CheckCircle2, XCircle, Clock, LogOut, Store, BarChart3, ArrowLeft } from 'lucide-react';

const ADMIN_EMAIL = 'zeus1404@gmail.com';
const ADMIN_AUTH_KEY = 'airctt_admin_auth';

interface AdminUser { email: string; name: string; picture: string; }
interface Coupon { id: string; title: string; description: string; discount_type: string; discount_value: number; approval_status: string; merchant_url: string; image_url: string; created_at: string; merchant_id: string; store_id: string; }
interface StoreItem { id: string; name: string; is_active: boolean; created_at: string; merchants: { id: string; name: string; type: string; } | null; }

export default function AdminDashboard() {
  const router = useRouter();
    const [adminUser, setAdminUser] = useState<AdminUser | null>(null);
      const [isAuth, setIsAuth] = useState(false);
        const [loading, setLoading] = useState(true);
          const [tab, setTab] = useState<'coupons'|'stores'|'stats'>('coupons');
            const [coupons, setCoupons] = useState<Coupon[]>([]);
              const [stores, setStores] = useState<StoreItem[]>([]);
                const [filter, setFilter] = useState('PENDING_APPROVAL');
                  const [processing, setProcessing] = useState<string|null>(null);
                    const [dataLoading, setDataLoading] = useState(false);
                      const [loginEmail, setLoginEmail] = useState('');
                        const [loginStep, setLoginStep] = useState<'email'|'verify'>('email');

                          useEffect(() => {
                              const saved = localStorage.getItem(ADMIN_AUTH_KEY);
                                  if (saved) {
                                        try {
                                                const u = JSON.parse(saved) as AdminUser;
                                                        if (u.email === ADMIN_EMAIL) { setAdminUser(u); setIsAuth(true); }
                                                                else { localStorage.removeItem(ADMIN_AUTH_KEY); }
                                                                      } catch { localStorage.removeItem(ADMIN_AUTH_KEY); }
                                                                          }
                                                                              setLoading(false);
                                                                                }, []);

                                                                                  const handleLogin = () => {
                                                                                      if (loginStep === 'email') {
                                                                                            if (loginEmail !== ADMIN_EMAIL) { alert('접근 권한이 없습니다. zeus1404@gmail.com만 가능합니다.'); return; }
                                                                                                  setLoginStep('verify');
                                                                                                      } else {
                                                                                                            const u: AdminUser = { email: ADMIN_EMAIL, name: '최종관리자', picture: '' };
                                                                                                                  localStorage.setItem(ADMIN_AUTH_KEY, JSON.stringify(u));
                                                                                                                        setAdminUser(u); setIsAuth(true);
                                                                                                                            }
                                                                                                                              };

                                                                                                                                const handleLogout = () => { localStorage.removeItem(ADMIN_AUTH_KEY); setAdminUser(null); setIsAuth(false); setLoginStep('email'); setLoginEmail(''); };

                                                                                                                                  const fetchCoupons = useCallback(async () => {
                                                                                                                                      setDataLoading(true);
                                                                                                                                          try { const r = await fetch('/api/admin/coupon-approvals'); const d = await r.json(); setCoupons(d.coupons || []); } catch(e) { console.error(e); }
                                                                                                                                              setDataLoading(false);
                                                                                                                                                }, []);

                                                                                                                                                  const fetchStores = useCallback(async () => {
                                                                                                                                                      setDataLoading(true);
                                                                                                                                                          try { const r = await fetch('/api/admin/stores'); const d = await r.json(); setStores(d.stores || []); } catch(e) { console.error(e); }
                                                                                                                                                              setDataLoading(false);
                                                                                                                                                                }, []);

                                                                                                                                                                  useEffect(() => { if (isAuth) { fetchCoupons(); fetchStores(); } }, [isAuth, fetchCoupons, fetchStores]);

                                                                                                                                                                    const handleAction = async (id: string, action: 'APPROVED'|'REJECTED') => {
                                                                                                                                                                        setProcessing(id);
                                                                                                                                                                            try {
                                                                                                                                                                                  const r = await fetch('/api/admin/coupon-approvals', { method: 'PATCH', headers: {'Content-Type':'application/json'}, body: JSON.stringify({coupon_id:id, action, admin_email:ADMIN_EMAIL}) });
                                                                                                                                                                                        if (r.ok) await fetchCoupons(); else alert('처리 실패');
                                                                                                                                                                                            } catch { alert('오류 발생'); }
                                                                                                                                                                                                setProcessing(null);
                                                                                                                                                                                                  };

                                                                                                                                                                                                    const filtered = coupons.filter(c => c.approval_status === filter);
                                                                                                                                                                                                      const pending = coupons.filter(c => c.approval_status === 'PENDING_APPROVAL').length;
                                                                                                                                                                                                        const approved = coupons.filter(c => c.approval_status === 'APPROVED').length;
                                                                                                                                                                                                          const rejected = coupons.filter(c => c.approval_status === 'REJECTED').length;

                                                                                                                                                                                                            if (loading) return <div className="min-h-screen bg-gray-950 flex items-center justify-center"><div className="animate-spin rounded-full h-12 w-12 border-t-2 border-purple-500"/></div>;

                                                                                                                                                                                                              if (!isAuth) return (
                                                                                                                                                                                                                  <div className="min-h-screen bg-gray-950 flex items-center justify-center p-4">
                                                                                                                                                                                                                        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-8 max-w-md w-full text-center shadow-2xl">
                                                                                                                                                                                                                                <div className="w-20 h-20 bg-gradient-to-br from-red-500 to-purple-600 rounded-full flex items-center justify-center mx-auto mb-6"><Shield className="w-10 h-10 text-white"/></div>
                                                                                                                                                                                                                                        <h1 className="text-2xl font-bold text-white mb-2">최종관리자 전용</h1>
                                                                                                                                                                                                                                                <p className="text-gray-400 mb-2">AIRCTT CouponTalkTalk</p>
                                                                                                                                                                                                                                                        <p className="text-red-400 text-sm mb-6">zeus1404@gmail.com 계정만 접근 가능</p>
                                                                                                                                                                                                                                                                {loginStep === 'email' ? (
                                                                                                                                                                                                                                                                          <div className="space-y-3">
                                                                                                                                                                                                                                                                                      <input type="email" value={loginEmail} onChange={e => setLoginEmail(e.target.value)} placeholder="Google 이메일 입력" className="w-full px-4 py-3 bg-gray-800 border border-gray-700 rounded-xl text-white placeholder-gray-500 focus:border-purple-500 focus:outline-none"/>
                                                                                                                                                                                                                                                                                                  <button onClick={handleLogin} className="w-full py-3 bg-gradient-to-r from-red-600 to-purple-600 hover:from-red-500 hover:to-purple-500 rounded-xl text-white font-medium">다음</button>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                          <p className="text-green-400 text-sm mb-2">✓ {ADMIN_EMAIL} 확인됨</p>
                                                                                                                                                                                                                                                                                                                                                      <input type="password" placeholder="Google 비밀번호 입력" className="w-full px-4 py-3 bg-gray-800 border border-gray-700 rounded-xl text-white placeholder-gray-500 focus:border-purple-500 focus:outline-none"/>
                                                                                                                                                                                                                                                                                                                                                                  <button onClick={handleLogin} className="w-full py-3 bg-gradient-to-r from-red-600 to-purple-600 hover:from-red-500 hover:to-purple-500 rounded-xl text-white font-medium">로그인</button>
                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => setLoginStep('email')} className="text-gray-500 text-sm">뒤로</button>
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => router.push('/merchant')} className="mt-6 text-gray-500 hover:text-gray-300 text-sm underline">머천트 페이지로 돌아가기</button>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="min-h-screen bg-gray-950 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                <header className="bg-gray-900/80 backdrop-blur border-b border-gray-800 sticky top-0 z-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => router.push('/merchant')} className="p-2 hover:bg-gray-800 rounded-lg"><ArrowLeft className="w-5 h-5"/></button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-8 h-8 bg-gradient-to-br from-red-500 to-purple-600 rounded-lg flex items-center justify-center"><Shield className="w-4 h-4"/></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div><h1 className="text-lg font-bold">최종관리자</h1><p className="text-xs text-gray-400">{adminUser?.email}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={handleLogout} className="flex items-center gap-2 px-3 py-1.5 hover:bg-gray-800 rounded-lg text-gray-400 hover:text-red-400 text-sm"><LogOut className="w-4 h-4"/>로그아웃</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="max-w-7xl mx-auto px-4 py-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-gray-900 border border-gray-800 rounded-xl p-4"><div className="flex items-center gap-2 mb-2"><Clock className="w-4 h-4 text-yellow-400"/><span className="text-xs text-gray-400">승인 대기</span></div><p className="text-2xl font-bold text-yellow-400">{pending}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-gray-900 border border-gray-800 rounded-xl p-4"><div className="flex items-center gap-2 mb-2"><CheckCircle2 className="w-4 h-4 text-green-400"/><span className="text-xs text-gray-400">승인됨</span></div><p className="text-2xl font-bold text-green-400">{approved}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-gray-900 border border-gray-800 rounded-xl p-4"><div className="flex items-center gap-2 mb-2"><XCircle className="w-4 h-4 text-red-400"/><span className="text-xs text-gray-400">거절됨</span></div><p className="text-2xl font-bold text-red-400">{rejected}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-gray-900 border border-gray-800 rounded-xl p-4"><div className="flex items-center gap-2 mb-2"><Store className="w-4 h-4 text-purple-400"/><span className="text-xs text-gray-400">등록 사업자</span></div><p className="text-2xl font-bold text-purple-400">{stores.length}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-2 mb-6 border-b border-gray-800 pb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {([['coupons','Ticket','쿠폰 승인'],['stores','Users','사업자 관리'],['stats','BarChart3','통계']] as const).map(([k,_,l]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button key={k} onClick={() => setTab(k as any)} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium ${tab===k?'bg-purple-600 text-white':'bg-gray-900 text-gray-400 hover:bg-gray-800'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {k==='coupons'&&<Ticket className="w-4 h-4"/>}{k==='stores'&&<Users className="w-4 h-4"/>}{k==='stats'&&<BarChart3 className="w-4 h-4"/>}{l}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {tab==='coupons'&&(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-2 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {[['PENDING_APPROVAL','승인 대기',pending],['APPROVED','승인됨',approved],['REJECTED','거절됨',rejected]].map(([k,l,c]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button key={k as string} onClick={() => setFilter(k as string)} className={`px-3 py-1.5 rounded-full text-xs font-medium ${filter===k?'bg-purple-500/20 text-purple-400 border border-purple-500/50':'bg-gray-900 text-gray-500'}`}>{l as string} ({c as number})</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {dataLoading?<div className="text-center py-12 text-gray-500">로딩 중...</div>:filtered.length===0?<div className="text-center py-12 text-gray-500">해당 상태의 쿠폰이 없습니다.</div>:(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-3">{filtered.map(c=>(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={c.id} className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {c.image_url&&<img src={c.image_url} alt="" className="w-16 h-16 rounded-lg object-cover"/>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex-1 min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="font-semibold text-white truncate">{c.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-gray-400 truncate">{c.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-xs text-purple-400">{c.discount_type==='PERCENTAGE'?`${c.discount_value}% 할인`:`${c.discount_value}원 할인`}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {c.approval_status==='PENDING_APPROVAL'&&<div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={()=>handleAction(c.id,'APPROVED')} disabled={processing===c.id} className="px-3 py-1.5 bg-green-600 hover:bg-green-500 rounded-lg text-xs font-medium disabled:opacity-50">승인</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={()=>handleAction(c.id,'REJECTED')} disabled={processing===c.id} className="px-3 py-1.5 bg-red-600 hover:bg-red-500 rounded-lg text-xs font-medium disabled:opacity-50">거절</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {tab==='stores'&&(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>{dataLoading?<div className="text-center py-12 text-gray-500">로딩 중...</div>:stores.length===0?<div className="text-center py-12 text-gray-500">등록된 사업자가 없습니다.</div>:(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-3">{stores.map(s=>(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={s.id} className="bg-gray-900 border border-gray-800 rounded-xl p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center justify-between"><h3 className="font-semibold text-white flex items-center gap-2"><Store className="w-4 h-4 text-purple-400"/>{s.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className={`px-2 py-0.5 rounded-full text-xs ${s.is_active?'bg-green-500/20 text-green-400':'bg-gray-700 text-gray-400'}`}>{s.is_active?'운영중':'비활성'}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {s.merchants&&<p className="text-sm text-gray-400 mt-1">사업자: {s.merchants.name} ({s.merchants.type})</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs text-gray-600 mt-1">등록일: {new Date(s.created_at).toLocaleDateString('ko-KR')}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {tab==='stats'&&(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-lg font-semibold mb-4 flex items-center gap-2"><BarChart3 className="w-5 h-5 text-purple-400"/>전체 현황</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-gray-800/50 rounded-lg p-4"><p className="text-sm text-gray-400">전체 쿠폰</p><p className="text-3xl font-bold">{coupons.length}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-gray-800/50 rounded-lg p-4"><p className="text-sm text-gray-400">전체 사업자</p><p className="text-3xl font-bold">{stores.length}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-gray-800/50 rounded-lg p-4"><p className="text-sm text-gray-400">승인율</p><p className="text-3xl font-bold text-green-400">{coupons.length>0?Math.round((approved/coupons.length)*100):0}%</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-gray-800/50 rounded-lg p-4"><p className="text-sm text-gray-400">대기중</p><p className="text-3xl font-bold text-yellow-400">{pending}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }